import argparse
import os
import shutil
from collections.abc import Sequence

import pandas as pd
import yaml


def parse_args(args: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate course tree",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "table",
        type=str,
        nargs="?",
        default="./results/table.csv",
        help="Path to the input table file (generated by filter.py)",
    )
    parser.add_argument(
        "--output-dir",
        "-o",
        type=str,
        default="./results/tree",
        help="Path to the output directory",
    )

    return parser.parse_args(args)


def get_rel_path(course_name: str, instructor: str) -> str:
    return f"courses/{course_name}/{instructor}.md"

def generate_content(
    course_name: str, instructor: str, course_id: str, term: str, major: str
) -> str:
    content = f"""\
# {course_name} - {instructor}

## 基本信息

- 课程号: `{course_id}`
- 任课教师: {instructor}
- 上课专业: {major}

## 课程评价

暂无

## 如何贡献

请查看[评价指南](../how-to-comment.md)了解如何评价课程！
"""
    return content

def main():
    args = parse_args()

    print(f"Input table: {args.table}")
    print(f"Output directory: {args.output_dir}")

    assert os.path.isfile(args.table), f"Input table file {args.table} does not exist"
    shutil.rmtree(args.output_dir, ignore_errors=True)
    os.makedirs(args.output_dir, exist_ok=True)
    courses = []
    courses_dict = {}
    for _, row in pd.read_csv(args.table).iterrows():
        course_name: str = row["CourseName"]
        instructor: str = row["Instructor"]
        course_id: str = row["CourseId"]
        term: str = row["Term"]
        major: str = row["SimplifiedMajor"]

        if course_name in courses_dict:
            course_top = courses_dict[course_name]
        else:
            course_top = []
            courses_dict[course_name] = course_top
            courses.append({course_name: course_top})

        relpath = get_rel_path(course_name, instructor)
        course_top.append({instructor: relpath})
        abspath = os.path.join(args.output_dir, relpath)
        os.makedirs(os.path.dirname(abspath), exist_ok=True)
        with open(abspath, "w") as f:
            f.write(generate_content(course_name, instructor, course_id, term, major))
        

    # generate yaml
    with open(os.path.join(args.output_dir, "nav.yaml"), "w") as f:
        yaml.dump({"nav": [{"选课指南": courses}]}, f, allow_unicode=True)


if __name__ == "__main__":
    main()
